version: '3.8'

services:
  db:
    image: postgres:10
    container_name: task
    restart: unless-stopped
    environment:
      POSTGRES_USER: use
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: task_app
#    restart: unless-stopped
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task
#      SPRING_DATASOURCE_USERNAME: use
#      SPRING_DATASOURCE_PASSWORD: password
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db

volumes:
  db_data: